#!/usr/bin/env sh

## LOCATION:     /etc/pacman.d/scripts/opendoas-install.sh
## AUTHOR:       AISK11
## DESCRIPTION:  Opendoas configuration.
## DEPENDENCIES: system/coreutils system/grep system/shadow

## Create doas group.
cat /etc/group | grep '^doas:' || groupadd doas

## Create doas configuration file.
cat << EOF > '/etc/doas.conf'
## LOCATION:     /etc/doas.conf
## AUTHOR:       Generated by "/etc/pacman.d/scripts/opendoas-install.sh"
## DESCRIPTION:  Privilege escalation permission file.
## DEPENDENCIES: galaxy/opendoas

## 1. If "doas" group is not in "/etc/group", create it:
##    \$(groupadd doas)
## 2. Add user to doas group:
##    \$(usermod -aG doas <USER>)

## Grand root permissions to "doas" group without requiring password.
permit nopass :doas
EOF
chmod 0600 /etc/doas.conf
exit 0
